- name: "filters"
  hosts: local
  connection: local
  vars:
    Topics: Ansible, Linux, Shell, Terraform
    COURSENAME: "DevOps with AWS"
    IP: "230.76.56.45"
    tagsMap:
      COURSE: Devops
      TRAINER: Meena
  tasks:
  - name: "Greetings"
    ansible.builtin.debug:
      msg: "Hi Meena, {{ GREETINGS | default('Good Morning') }}"
  
  - name: "String to List"
    ansible.builtin.debug:
      msg: "{{ Topics | split(',') }}"

  - name: "Map to List"
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: "Set the file to variable"
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'students.yaml') | from_yaml }}" 
 
  - name: "Yaml to json"
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"

  - name: "upper"
    ansible.builtin.debug:
      msg: "{{ COURSENAME | upper }}"
    
  - name: "lower"
    ansible.builtin.debug:
      msg: "{{ COURSENAME | lower }}"

  - name: "IPV4"
    ansible.builtin.debug:
      msg: "{{ IP | ansible.utils.ipv4 }}"


  