- name: "Check user for idempotency"
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: "Check user"
    ansible.builtin.user:
      user: roboshop

  - name: "Add user"
    ansible.builtin.command: useradd roboshop
    register: useradd_output