192.34.56.78

[frontend]
192.34.56.71
192.34.56.72

[backend]
192.34.56.73
192.34.56.74

[roboshop:children]
frontend
backend

[localhost]
local

[local:vars]
COURSE="Inventory Variables"
TRIANER="Meena"